name = "Techno-Celestial Warfare"
author = "null squad at bethetka.ru"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a325177f3de668f6d3d475776e585ed3064d1ad6d15ac994045a1e80e2b7eeb"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
