name = "Techno-Celestial-Warfare"
author = "null squad at bethetka.ru"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7a710c1cf2874e70522a67716152cc4c688f0199d52ffab5733878efdf4281b"

[versions]
forge = "40.2.14"
minecraft = "1.18.2"
